under10000/board/urls.py
from django.urls import path
from . import views

# hhtp://localhost/board/
app_name = "board"
urlpatterns = [
    path("", views.board_list, name="board_list"),
    path("write/", views.board_write, name="board_write"),
    path("detail/<int:pk>/", views.board_detail, name="board_detail"),
    path("detail/<int:pk>/delete/", views.board_delete, name="board_delete"),
    path("detail/<int:pk>/modify/", views.board_modify, name="board_modify"),
]

under10000/under10000/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("", RedirectView.as_view(url="/home/", permanent=True)),
    path("board/", include("board.urls")),
]

# summernote 설정
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [path("summernote/", include("django_summernote.urls"))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

under10000/board/models.py
from django.db import models
import os
from django.conf import settings

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=64, verbose_name="title")
    contents = models.TextField(verbose_name="contents")
    writer = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, verbose_name="writer"
    )
    write_dttm = models.DateTimeField(auto_now_add=True, verbose_name="upload Date")

    board_name = models.CharField(
        max_length=32, default="Python", verbose_name="board category"
    )
    update_dttm = models.DateTimeField(auto_now=True, verbose_name="lastest updated")
    hits = models.PositiveIntegerField(default=0, verbose_name="hits")

    def __str__(self):
        return self.title

    class Meta:
        db_table = "board"
        verbose_name = "board"
        verbose_name_plural = "board"


class PostHits(models.Model):
    client_ip = models.GenericIPAddressField(
        protocol="both", unpack_ipv4=False, null=True, verbose_name="User IP Addrress"
    )
    date = models.DateField(auto_now_add=True, verbose_name="Hit date")
    post = models.Foreignkey("Board", on_delete=models.CASCADE, verbose_name="post")

    def __str__(self):
        return str(self.post.id)

    class Meta:
        db_table = "post_hits"
        verbose_name = "hits model"
        verbose_name = "hits model"

under10000/board/forms.py
from django import forms
from .models import Board
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class BoardWriteForm(forms.ModelForm):
    title = forms.CharField(
        label="Title",
        widget=forms.TextInput(
            attrs={"placeholder": "Title of Contents"},
        ),
        required=True,
    )

    contents = SummernoteTextField()

    options = (
        ("Python", "Python Board"),
        ("JavaScript", "JavaScript Board"),
    )

    board_name = forms.ChoiceField(
        label="Choose Board",
        widget=forms.Select(),
        choices=options,
    )

    field_order = [
        "title",
        "board_name",
        "contents",
    ]

    class Meta:
        model = Board
        fields = [
            "title",
            "contents",
            "board_name",
        ]
        widgets = {
            "contents": SummernoteWidget(),
        }

    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get("title", "")
        contents = cleaned_data.get("contents", "")
        board_name = cleaned_data.get("board_name", "Python")

        if title == "":
            self.add_error("title", "Please fill in the title.")
        elif contents == "":
            self.add_error("contents", "Please write contents.")
        else:
            self.title = title
            self.contetns = contents
            self.board_name = board_name

under10000/board/views.py
from django.shortcuts import render, redirect
from .forms import BoardWriteForm
from .models import Board
from users.models import User
from users.decorators import login_required
from django.shortcuts import get_object_or_404
from datetime import date, datetime, timedelta

# Create your views here.
def board_list(request):
    login_session = request.session.get("login_session", "")
    context = {"login_session": login_session}

    py_boards = Board.objects.filter(board_name="Python")
    js_boards = Board.objects.filter(board_name="JavaScript")

    context["py_boards"] = py_boards
    context["js_boards"] = js_boards
    return render(request, "board/board_list.html", context)


@login_required
def board_write(request):
    login_session = request.session.get("login_session", "")
    context = {"login_session": login_session}

    if request.method == "GET":
        write_form = BoardWriteForm()
        context["forms"] = write_form
        return render(request, "board/board_write.html", context)

    elif request.method == "POST":
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            writer = User.objects.get(user_id=login_session)
            board = Board(
                title=write_form.title,
                contents=write_form.contents,
                writer=writer,
                board_name=write_form.board_name,
            )
            board.save()
            return redirect("/board")
        else:
            context["forms"] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context["error"] = value
            return render(request, "board/board_write.html", context)


def board_detail(request, pk):
    login_session = request.session.get("login_session", "")
    context = {"login_session": login_session}

    board = get_object_or_404(Board, id=pk)
    context["board"] = board

    # 글쓴이인지 확인
    if board.writer.user_id == login_session:
        context["writer"] = True
    else:
        context["writer"] = False

    # 조회수 기능(쿠키이용)
    expire_date, now = datetime.now(), datetime().now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replacae(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_second()

    cookie_value = request.COOKIES.get("hitboard", "_")

    if f"_{pk}_" not in cookie_value:
        cookie_value += f"{pk}_"
        response.set_cookie(
            "hitboard", value=cookie_value, max_age=max_age, httponly=True
        )
        board.hits += 1
        board.save()
    return response

    return render(request, "board/board_detail.html", context)


def board_delete(request, pk):
    login_session = request.session.get("login_session", "")
    board = get_object_or_404(Board, id=pk)
    if board.writer.user_id == login_session:
        board.delete()
        return redirect("/board")
    else:
        return redirect(f"/board/detail/{pk}/")


@login_required
def board_modify(request, pk):
    login_session = request.session.get("login_session", "")
    context = {"login_session": login_session}

    board = get_object_or_404(Board, id=pk)
    context["board"] = board

    if board.writer.user_id != login_session:
        return redirect(f"/board/detail/{pk}/")

    if request.method == "GET":
        write_form = BoardWriteForm(instance=board)
        context["forms"] = write_form
        return render(request, "board/board_modify.html", context)

    elif request.method == "POST":
        write_form = BoardWriteForm(request.POST)

        if write_form.is_valid():
            board.title = write_form.title
            board.contents = write_form.contents
            board.board_name = write_form.board_name

            board.save()
            return redirect("/board")
        else:
            context["forms"] = write_form
            if write_form.errors:
                for value in write_form.errors.value():
                    context["error"] = value

            return render(request, "board/board_modify.html", context)

under10000/board/templates/board/board_detail.html
{% extends 'homepage/index.html' %}

{% block contents %}
<div>Board Detail</div>

{% if writer %}
<a href="/board/detail/{{ board.id }}/modify/"><button>Edit</button></a>
<a href="/board/detail/{{ board.id }}/delete/"><button>Delete</button></a>
{% endif %}
<div>
    Board Category : {{ board.board_name }}
</div>
<div>
    Writer : {{ board.writer }} | Date : {{ board.write_dttm }} | hits : {{ board.hits }}
</div>
<div>
    Title : {{ board.title }}
</div>
<div>
    Contents : {{ board.contents|safe }}
</div>

{% endblock contents %}

under10000/board/templates/board/board_list.html
{% extends 'homepage/index.html' %}

{% block contents %}
<div>Board</div>
<div><a href="{% url 'board:board_write' %}"><button>Write</button></a></div>

<div class="board">
    <div class="py_boards">
        <p>(Python Board)</p>
        {% for board in py_boards %}
        {% if board %}
        <a href="/board/detail/{{ board.id }}" target="'_self">
            <div>{{ board.title }} / {{ board.writer }} / {{ board.write_dttm }}</div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <div class="js_boards">
        <p>(JavaScript Board)</p>
        {% for board in js_boards %}
        {% if board %}
        <a href="/board/detail/{{ board.id }}" target="'_self">
            <div>{{ board.title }} / {{ board.writer }} / {{ board.write_dttm }}</div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
</div>

<style>
    .board{
        display: flex;
    }

    .py_boards {
        width: 50%;
    }

    .js_boards {
        width: 50%;
        border-left: 2px black double;
        padding-left: 25px;
    }

</style>
{% endblock contents %}

under10000/board/templates/board/board_modify.html
{% extends 'homepage/index.html' %}

{% block contents %}
<div>Edit Board</div>
<form action="", method="POST">
    {% csrf_token %}
    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %}

    {% if error %}
    {{ error }}
    {% endif %}
    <button type="'submit">Edit</button>


</form>
{% endblock contents %}

under10000/board/templates/board/board_write.html
{% extends 'homepage/index.html' %}

{% block contents %}
<div>Write Board</div>
<form action="", method="POST">
    {% csrf_token %}
    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
        {{ form }}
    </div>
    {% endfor %}

    {% if error %}
    {{ error }}
    {% endif %}
    <button type="'submit">Submit</button>


</form>
{% endblock contents %}