under10000/board/urls.py
from django.urls import path
from . import views

# hhtp://localhost/board/
app_name = "board"
urlpatterns = [
    path("", views.board_list, name="board_list"),
    path("write/", views.board_write, name="board_write"),
    path("detail/<int:pk>/", views.board_detail, name="board_detail"),
    path("detail/<int:pk>/delete/", views.board_delete, name="board_delete"),
    path("detail/<int:pk>/modify/", views.board_modify, name="board_modify"),
]

under10000/homepage/urls.py
from django.contrib import admin
from django.urls import path

from . import views

# app urls down here
app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index"),
]

under10000/under10000/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("homepage.urls")),
    path("users/", include("users.urls")),
    path("", RedirectView.as_view(url="/home/", permanent=True)),
    path("board/", include("board.urls")),
]

# summernote 설정
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += [path("summernote/", include("django_summernote.urls"))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

under10000/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# http://localhost/users
app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

under10000/homepage/models.py
from django.db import models

# Create your models here.

under10000/homepage/views.py
from django.shortcuts import render
from users.models import User

# Create your views here.


def index(request):
    context = {}

    login_session = request.session.get("login_session", "")

    if login_session == "":
        context["login_session"] = False
    else:
        context["login_session"] = True

    return render(request, "homepage/index.html", context)

under10000/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" contetn="width=device-width, initial-scale=1.0">
    <title>Under10000</title>
</head>
<body>
    <h1>Hello World</h1>
    <a href="/"><button>Home</button></a>
    <a href="{% url 'board:board_list' %}"><button>Board</button></a>

    {% if login_session %}
    <a href="{% url 'users:logout' %}"><button>Logout</button></a>
    {% else %}
    <a href="{% url 'users:login' %}"><button>Login</button></a>
    <a href="{% url 'users:register' %}"><button>Sign Up</button></a>
    {% endif %}
    {% block contents %}
    {% endblock contents %}
</body>


</html>